/**
 * @file carFactory.hpp
 * @author Ryan Buutler (rmbutler@outlook.com)
 * @brief Defines the interface for a car factory
 * @version 0.1
 * @date 2025-07-13
 * 
 * @copyright Copyright (c) 2025
 * 
 */
#pragma once

#include <memory>
#include <random>
#include "car.hpp"

class CarFactory {

protected: 
    std::normal_distribution<double> politeness_dist_; ///< Distribution of politeness values for the cars
    mutable size_t carid_; ///< Car id of the next car to be generated

public:
    
    /**
     * @brief Construct a new Car Factory object with a mean politeness and politeness standard deviation. 
     * 
     * @param politeness Mean politeness value of all cars generated by the factory
     * @param p_stdev Standard deviation of the politeness of all cars generated. 
     */
    CarFactory(double politeness, double p_stdev);
    virtual ~CarFactory() = default;

    /**
     * @brief Generates a car from this factory. The car's position, velocities and timestamp are the arguments
     * to this function, the politeness comes from the politeness data member variables and the follow
     * model comes from the data in the derived classes. 
     * 
     * @param x0 Initial position of the car.
     * @param v0 Initial car velocity
     * @param vdes Desired velocity of the car
     * @param t0 (optional) The initial timestamp of the car
     * @return Car 
     */
    virtual Car makeCar(double x0, double v0, double vdes, double t0 = 0) = 0;
};

class GippsCarFactory : public CarFactory {
    std::mt19937 rng_;
    std::normal_distribution<double> a_dist;
    std::normal_distribution<double> b_dist;
    std::normal_distribution<double> bmax_dist;

    public: 
    GippsCarFactory(double a, double b, double bmax, double p,
                    double a_stdev , double b_stdev , double bmax_stdev, double p_stdev,
                    size_t seed);

    ~GippsCarFactory() = default;

    Car makeCar(double x0, double v0, double vdes, double t0) override;
};

class IDMCarFactory : public CarFactory {

    std::mt19937 rng_;
    std::normal_distribution<double> a_dist;
    std::normal_distribution<double> b_dist;
    std::normal_distribution<double> s0_dist;

    public: 
    IDMCarFactory(double a, double b, double s0, double p,
        double a_stdev , double b_stdev , double s0_stdev, double p_stdev,
        size_t  seed);
    ~IDMCarFactory() = default;

    Car makeCar(double x0, double v0, double vdes, double t0) override;
};